dist: xenial
language: cpp
compiler: clang

install:
  - sudo apt-get remove --auto-remove python-enum34
  - sudo pip install --upgrade pip
  - sudo pip install conan
  - conan user

before_script:
- sudo apt update
- sudo apt install libboost-test-dev -y

script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script: curl -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulonforton:$BINTRAY_API_KEY "https://api.bintray.com/content/lonforton/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
